# Generated by Django 3.2.7 on 2022-05-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='total',
            field=models.FloatField(default=0, null=True, verbose_name='Table Total Amount'),
        ),
    ]
