# Generated by Django 3.2.7 on 2022-05-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_alter_table_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='rezerve',
            field=models.BooleanField(default=False),
        ),
    ]
